### ISSUE TITLE
Obsolete PATO terms in OBI

### ISSUE THREAD

**Issue by pbuttigieg** [obi-ontology/obi#973] opened 2018-10-07 22:31 UTC
Detected in [ENVO build process](https://travis-ci.org/EnvironmentOntology/envo/builds/437240177#L754)

The PATO import in OBI for [`quality of related physical entities`](http://www.ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/PATO_0001238) (and other PATO classes) is now [obsolete ](http://purl.obolibrary.org/obo/PATO_0001238)

Refresh imports?

@cmungall - related to the modularisation task

**Comment by bpeters42** [comment] 2018-10-08 16:55
Discussed on call 10/8. Very True! We will update OBI to reflect a number of changes in PATO that we have not carried through, and stop doing 'manual imports' of obsoleted PATO terms (originally requested by Alan Ruttenberg).  Jie or James will implement.

**Comment by zhengj2007** [comment] 2019-03-11 16:37
Discussed on Mar 11, 2019 OBI call. @zhengj2007 will take care of it.

**Comment by rctauber** [comment] 2019-03-21 15:10
This seems to be a duplicate of #826

**Comment by zhengj2007** [comment] 2019-03-28 15:27
Planning to make following changes:
http://www.ontobee.org/ontology/PATO?iri=http://purl.obolibrary.org/obo/PATO_0001237 and
http://www.ontobee.org/ontology/PATO?iri=http://purl.obolibrary.org/obo/PATO_0001238
merged to
http://purl.obolibrary.org/obo/PATO_0001241
physical object quality
So, should be replaced by PATO_0001241.

http://purl.obolibrary.org/obo/PATO_0001631
was replaced by
http://purl.obolibrary.org/obo/PATO_0000140
position

However, if we make those changes, many PATO terms which are subClasses of 'physical object quality' in PATO become its sibling in OBI. Propose to use another Ontofox import option to import the PATO terms into OBI. I will work on it and show it on the future OBI call.

**Comment by zhengj2007** [comment] 2019-06-03 16:27
Discussed on June 3rd, 2019 OBI call.

Agree to update the import hierarchy via OntoFox for qualities from PATO under physical object quality.

**Comment by zhengj2007** [comment] 2019-10-28 17:02
Done.

**Closed by zhengj2007** 2019-10-28 17:02 UTC
